### ISSUE TITLE
Come viene gestita la lingua?

### ISSUE THREAD

**Issue by karimone** [efphe/wupress#1]
Ho un sito wordpress che e' multilingua, ma il plugin sembra prendere solo l'impostazione del browser.

**Comment by steel--wubook** [comment]
Ciao,

il plugin, di default, prende le impostazioni di lingua del browser. Questo perché il sito potrebbe essere tradotto in lingue che non sono presenti o non sono gestite dalla reception online (in quei casi viene rispettata la lingua di failback impostata).

Questa scelta è stata fatta perché un utente che atterrà su una pagina che non è nella sua lingua, abbia comunque facilità ad individuare l'elemento che lo porta a prenotare.

È comunque possibile forzare una lingua di default dalle impostazioni nel backend, ma in questo caso sarà sempre l'unica lingua visibile.

Un'altra alternativa è l'implementazione personalizzata all'interno del tema, qui di seguito la documentazione:

http://tdocs.wubook.net/ord.html

In particolare, vedi i capitoli "Online Reception HTML Specification" e "Online Reception: WuBook’s Javascript Library".

Se serve altro sono a disposizione.

**Comment by karimone** [comment]
Intanto ti ringrazio per la disponibilita'. Ho il sito di un mio amico che usa WPML per gestire piu' lingue e vorrei che il settaggio della lingua di WPML abbia priorita' sul settaggio del browser. Il motivo dietro questa scelta e' dovuto dal fatto che i clienti che usano il widget generalmente non sono di fronte al loro computer. Ora mi vedo il codice che mi hai linkato. Grazie

**Comment by karimone** [comment]
Scusa se ti disturbo di nuovo, ma io non ho idea di come funzioni wordpress. Ho fatto dei test nella console di javascript e se eseguo questo comando:

```
WuBook.design_widget("__wubookwidget__", {lang:icl_lang})
```

Esegue esattamente cosa mi serve. La variabile icl_lang e' settata in JS dal plugin WPML. Ora come posso fare che nel plugin invece di prendere come lingua WP_LANG? Ho visto che wpml setta una variabile ICL_LANGUAGE_CODE.

Quindi io penso che sarebbe interessante mettere un'opzione in piu' nel setting di usare WPML se viene rilevato. Nel codice non riesco bene a capire come viene inizializzato il widget, in teoria  non dovrei mandare $ICL_LANGUAGE_CODE all'opzione 'lang' nell'array data (vedi da linea 462 in poi)

**Comment by karimone** [comment]
Risolto usando il JS nel template perche' il plugin WPML che viene usato e' troppo vecchio.

In teoria con nuove versione di WPML basterebbe includere nelle options della lingua di usare wpml e settare lang con il valore della constante ICL_DEFAULT_LANGUAGE.
